let balance=Number(localStorage.getItem("lg_balance"))||10000,rouletteBet=100,chosenColor=null,chosenNumber=null,history=[],slotBet=10,slotType="fruit",crashBet=100,crashTimer=null,crashRunning=false,crashMult=1;
const slots={fruit:{name:"🍒 Fruit Party",lines:3,s:["🍒","🍋","🍊","🍉","⭐"]},diamond:{name:"💎 Diamond 9",lines:9,s:["💎","💰","7️⃣","👑","🔱"]}};
function fmt(n){return Math.floor(n).toLocaleString("ru-RU")}function save(){localStorage.setItem("lg_balance",balance)}function upd(){balance=Math.max(0,balance);document.getElementById("balance").textContent=fmt(balance);save()}function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
function openPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");document.body.classList.toggle("lock",id==="roulette");scrollTo(0,0)}
function buildWheel(){let e=document.getElementById("wheelNumbers"),n=document.getElementById("numbers");e.innerHTML="";n.innerHTML="";for(let i=0;i<37;i++){let s=document.createElement("span");s.textContent=i;s.style.transform=`rotate(${i*9.73-90}deg) translateX(100px) rotate(${90-i*9.73}deg)`;e.appendChild(s);let b=document.createElement("button");b.textContent=i;b.onclick=()=>pickNumber(i,b);n.appendChild(b)}}
function pickNumber(n,b){chosenNumber=n;document.querySelectorAll(".numbers button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");showSelected()}
function setColor(c){chosenColor=c;showSelected()}function showSelected(){document.getElementById("selected").textContent="Ставка: "+(chosenColor?chosenColor:"цвет — нет")+" • "+(chosenNumber!==null?"число "+chosenNumber:"число — нет")}
function adjust(v){rouletteBet=Math.max(100,Math.min(5000,rouletteBet+v));document.getElementById("rbet").textContent=fmt(rouletteBet)}
function spinRoulette(){if(chosenColor===null&&chosenNumber===null){toast("Выберите цвет или число");return}if(balance<rouletteBet){toast("Недостаточно виртуальных монет");return}balance-=rouletteBet;upd();let wrap=document.querySelector(".rouletteWrap");wrap.classList.remove("spinning");void wrap.offsetWidth;wrap.classList.add("spinning");setTimeout(()=>{let n=Math.floor(Math.random()*37),color=n===0?"green":([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36].includes(n)?"red":"black");wheelResult.textContent=n;let win=0;if(chosenNumber===n)win+=rouletteBet*35;if(chosenColor===color)win+=rouletteBet*(color==="green"?14:2);if(win){balance+=win;rouletteMsg.textContent="🎉 Выпало "+n+" • выигрыш "+fmt(win)}else rouletteMsg.textContent="Выпало "+n+" • "+color+" • ставка проиграла";history.unshift(n);history=history.slice(0,8);document.getElementById("history").textContent="Последние: "+history.join(" • ");upd();wrap.classList.remove("spinning")},3850)}
function openSlot(t){slotType=t;openPage("slot");let c=slots[t];slotTitle.textContent=c.name;updateSlot()}function updateSlot(){let c=slots[slotType];slotBet.textContent=fmt(slotBet);reels.innerHTML=c.s.slice(0,3).map(x=>`<div>${x}</div>`).join("");slotMsg.textContent=c.lines+" линии • ставка за линию "+fmt(slotBet)}
function spinSlot(){let c=slots[slotType],cost=slotBet*c.lines;if(balance<cost){toast("Недостаточно виртуальных монет");return}balance-=cost;upd();let i=0,iv=setInterval(()=>{reels.innerHTML=[0,1,2].map(()=>`<div>${c.s[Math.random()*c.s.length|0]}</div>`).join("");if(++i>12){clearInterval(iv);let a=[0,1,2].map(()=>c.s[Math.random()*c.s.length|0]);reels.innerHTML=a.map(x=>`<div>${x}</div>`).join("");if(a[0]===a[1]&&a[1]===a[2]){let w=cost*(a[0]==="💎"?12:8);balance+=w;slotMsg.textContent="🎉 Выигрыш +"+fmt(w)}else slotMsg.textContent="Результат: "+a.join(" ");upd()}},65)}
function buyBonus(){let c=slots[slotType],cost=slotBet*c.lines*12;if(balance<cost){toast("Недостаточно виртуальных монет");return}balance-=cost;let w=cost*(1.5+Math.random()*3);balance+=Math.floor(w);upd();toast("🔥 Бонус-игра принесла "+fmt(w)+" виртуальных монет")}
function startCrash(){if(crashRunning||balance<crashBet){toast("Недостаточно виртуальных монет");return}balance-=crashBet;upd();crashRunning=true;crashMult=1;mult.textContent="1.00x";crashState.textContent="Самолёт летит…";start.disabled=true;take.disabled=false;let target=+(1.05+Math.random()*8.95).toFixed(2);crashTimer=setInterval(()=>{crashMult=+(crashMult+.03+crashMult*.008).toFixed(2);mult.textContent=crashMult.toFixed(2)+"x";if(crashMult>=target)endCrash()},80)}
function takeCrash(){if(!crashRunning)return;balance+=Math.floor(crashBet*crashMult);upd();toast("✈️ Выигрыш забран");endCrash(true)}
function endCrash(win=false){clearInterval(crashTimer);crashRunning=false;start.disabled=false;take.disabled=true;if(!win)crashState.textContent="💥 Краш на "+crashMult.toFixed(2)+"x"}
function daily(){let d=new Date().toISOString().slice(0,10);if(localStorage.getItem("lg_daily")===d){toast("Бонус уже получен");return}localStorage.setItem("lg_daily",d);balance+=1000;upd();toast("+1 000 виртуальных монет")}
function promo(){let c=code.value.trim().toUpperCase();if(localStorage.getItem("lg_promo")){promoMsg.textContent="Промокод уже использован";return}if(c==="LUCKY1000"||c==="DEMO500"){let n=c==="LUCKY1000"?1000:500;balance+=n;localStorage.setItem("lg_promo","1");upd();promoMsg.textContent="Активировано: +"+fmt(n)}else promoMsg.textContent="Неверный промокод"}
function spawnBonus(){let e=document.getElementById("bonusFly");e.style.display="flex";e.style.left=(10+Math.random()*75)+"%";e.style.top=(15+Math.random()*65)+"%";e.textContent="🎁";e.onclick=()=>{let n=100+Math.floor(Math.random()*901);balance+=n;upd();e.style.display="none";toast("🎁 Пойман бонус +"+fmt(n))};setTimeout(()=>{if(e.style.display!=="none")e.style.display="none"},6000)}
buildWheel();upd();updateSlot();setInterval(spawnBonus,12000);